esphome:
  name: card-reader

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

rc522_spi:
  cs_pin: GPIO21

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

wifi:
  ssid: !secret wifi
  password: !secret wifi_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Card-Reader Fallback Hotspot"
    password: "e1dlZpy34fhG"

captive_portal:

binary_sensor:
  - platform: rc522
    uid: 2C-75-E4-1F
    name: "Circle sticker tag"
